dist: xenial
sudo: required
language: python
cache: pip
python:
- 3.6.6
before_install:
- echo -e "machine github.com\n  login $GH_TOKEN" > ~/.netrc
install:
- echo "Installing dependencies"
- sudo apt-get update
- wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh
- bash miniconda.sh -b -p $HOME/miniconda
- export PATH="$HOME/miniconda/bin:$PATH"
- hash -r
- conda config --set always_yes yes --set changeps1 no
- conda update -q conda
- conda info -a
- conda create --name ta1-test-env python=3.6
- source activate ta1-test-env
- sudo apt-get install libgnutls28-dev
- chmod a+x .travis/pip_install.sh
- .travis/pip_install.sh
script:
- echo "Generating primitive description json and pipelines"
- cd .travis
- git clone https://${GH_TOKEN}@github.com/usc-isi-i2/dsbox-unit-test-datasets.git
- python genreate-pipelines-json.py
after_success:
  - echo "check succeed."
  - chmod a+x ./push.sh
  - ./push.sh
env:
  global:
  - secure: KYxD+0C79e7C3WkyuBM3q3NCgnhS0qd7zRxym6ZcEJEzQPsWjRuEGICg70EbKcCuKDUM5lgRZl4ueC8sriqeKmftYwckfd8PVHMr86jLie4vi6u69Fntxrp6K6CD6QL1d52Gi4ETtfX4O3qVXYmjNkwMViOZDHwEsKJMkO0v7wswSPb2OOnbqSU9Sm7SiQqQguflvVd25wpR9LnG6aprOi8zkWrgyA4AKQQH60I489A9XC+UKi7z84vtUh0PccHg/HBkmVkLC2WYYtrs805HP+Lmpd8v6coNRdZxucMqTEww4APBR0wSkC+uA4Tj35Tg2nLfDJDUgxb/xBTo6GyRoEWuJZ/pS889+qhUMJrhXvMf+4OrhnZ95J9GT+SXdetsqpL+STpiX8i3KrXTqHS6rRQB5LkRYTKKS0yWASyuYj+GYxg9EIgtYxCeXJ+YQ8icxRYRA9kPkDnBYPVYM0uICVuRaPSU8kk27KeKH120Rz5KJG8oUKra1meXkmPwDt/oNUlBTsa7LT1SDCrztgIP9wrVg0WQTaOwyjxetlFtmtQCKEX6Ulxp7rDh7JMng7KCIw4px7PxnofrJ7Et6ZwcI/GENn5eEdE1dna58Cg/q9Wa+gA6FdHsg7BxYmEw2AVZ4rz+fYDvQrI/B3id8VITc/n1DuvrXf0fjN7iy60e6zU=
  - secure: lb1aBFLSWn84QylypTxwVECxtNcGvUhmJZUPeGIHpL21SdnV97cjzv41zml/PtR4P6mm0KDyTHU8iUc6ZzZXcZvrCgU4Mo2PBSAxGww2MFXQ2Ex8ikFbiiHt5CuzMHSXfjVJwcRIB6CxyZrizH0qideyjAJriTYoZS2fYFS32XWd7NLwVyImTaBIZaki6KuCGt3aU8gHKEGCCT13XuXaxXRZ1kJuQKk6MDCTywN5TooLbjsYUTs2GHwIvr1gZI/nRsVExgzJnHmu2vg413WM+qVnaPL1E0RTOK+mlfsPSNptHxAqlUKHiLQYXbqpr92hx3xaEwSqdwWI8ZOd769AaWpz5htDJqeHrljpCv1LQl9mn4GJKd1Mayk9pEKKbWTerQqf2Pnjl6nnHFyB+jPanw8K85Mc4mYCS6u/6h8IiooXULg8M3qGlnuON3xQKxqxGjEnOpKgLCPPohHVtuih0Zp1FsNxC8O5J0MqBeexcFJdGcG3TS3vgq+76h9GzhFBU10PtcsEcSNIqqAnOwds8IDxFDYbLw50i3VoAAwQYb2KWLtXsSNLFuYbzvgcs4XUE9WzOMD0uAdbueaeU3A+iEtUBbnO2vNCQURljxwKkTjJ4+wE8BS128hgkXo+Xvo7dV4jT4ccxPfe7IEP6495fqeg0QVm9IEFhIn3GD5Y+os=
  - secure: QP+al2phdCPAvXKCcDiDF80zlyeGWG9srpdXqfgGLjR0Jcnc6/EmQvNCRJda7CXwAuMYYyBWE69yt22fOH1hHCBWUS5JwGt3YXTlA2hKqwvqmfAdpqM7jBzggdQ/jqzn7gotuRdVgsrWHvtEq6zKmaHV4yrFUKAmYuT8I3VgWJbYwMu9gFAfDxjgfbTkgBitBJgIeoqRYeQS4Q9LVLo/EQghylkHrAVqTvAA/rTR3I17ZTBpJBq9QfzMw1ihXv9osHEKhOoTfZ860p6I7qAR1fD/bv3dvTxLuOzQyUINUP/+nfjV0TCNxnwW00pxhCAa9DHp6OYu2GTVvVbfBxLKDdOfi9MLWk0b35I/jh3gXTNiZWAO0gdzOhnLuzGSRU0VnfiAUuy5GtsQZhxPWvPw1fxfeNCkBxC9reEVaOzpFrK15b+LcY4jvjHzfycVQ3ha79JUzZv1YAvkZSXPChA7z0fglVNsoysS7wuf8snJUg2GMij3I4oQsQfdcjRDvPbjp3nB0JN6MSojzkSC2D/qKFO1ONgDi7LAaZoJ2F78DPn5pUwG1Z74Ei7L9UH8diFn917LtLcO0G5RICElR2Rz8HpFpccPP5He0X8H4Y80xcF99IGewUV1dxApCNAS0yZpQH8wDFeO/NvbJGQCUCcrsdvZYeMipOE21ipG8AQsmH8=
  - secure: WknBw+JINoijvuFdppTF6mUQFtgqMpLZgIyj6kAW1Ucn+DM+f+0jkB3YUukGLeiDkYz8EpmppVwGx21J74GpN78+2hFtMHk0CfMePI6ouUfuScBzam4BB3TUxAp4GMJNAWbk6x1W+64I45hxSfjoipDxoRnrwzxi7vtjdnHB0vBucS5ITQ0Sc9yXhgWLTDf3zgLtgoEzECljQYmK84W5s1hmsgZekjgbYqEJ1LxFsa8wgvUmbavQ6EDjbd8zV32YBqYQgM/fnhMdX+RpWFlN/WPanoWLsHGRJ0sxCjFFZcvxvaomeYAi6VgLmU46TWMWmQQeOpwjubvO2rAlw4902Qc3AJeW2Ezs1vgukhaqvneU4G/xloJxz2//6y9UFB5jOlI1tqKkzzdERIgvsi93/bPQhl9NYg1+aJR+P16Z4Ia5jQetuzm4LRY1jt7K7yvIxqY/D2GuxrEsrgjXsCQXEEw884kDtvbbUxfwuD25VpJsB20OgCEMWqCUV5E/iKlE06V954gcGeJgpU+NokPsFzpo8JsKaqA7WfJlBTFPVuJ6VZIZsrv8GUSRyDAkQ6rT702h1/vFIdWV9d4ZjfshM95q6bZN4RsJXnXO47YGIez4rSKg0nsqOlbPZsh/z9AGLSdR6UBeoFvhKduIaxbyVj9/9XYfRUoulg6dYqaQw9A=
