dist: xenial
sudo: required
language: python
cache: false
python:
- 3.6.6
install:
- echo "Installing dependencies"
- sudo apt-get update
- wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh
- bash miniconda.sh -b -p $HOME/miniconda
- export PATH="$HOME/miniconda/bin:$PATH"
- hash -r
- conda config --set always_yes yes --set changeps1 no
- conda update -q conda
- conda info -a
- conda create --name ta1-test-env python=3.6
- source activate ta1-test-env
- sudo apt-get install libgnutls28-dev
- pip install -e git+https://gitlab.com/datadrivendiscovery/d3m@master#egg=d3m
  --progress-bar off
- pip install -e git+https://gitlab.com/datadrivendiscovery/common-primitives@master#egg=common-primitives
  --progress-bar off
- pip install -e git+https://gitlab.com/datadrivendiscovery/sklearn-wrap@dist#egg=sklearn-wrap
  --progress-bar off
- pip install -e git+https://github.com/usc-isi-i2/dsbox-cleaning@devel#egg=dsbox-datacleaning
  --progress-bar off
- pip install -e git+https://github.com/usc-isi-i2/dsbox-featurizer@devel#egg=dsbox-featurizer
  --progress-bar off
- pip install -e git+https://github.com/brekelma/dsbox_corex@master#egg=dsbox_corex
  --progress-bar off
- pip install psutil==5.4.7
before_script:
- git clone https://${GH_TOKEN}@github.com:usc-isi-i2/dsbox-unit-test-datasets.git
# - python .travis/download_datasets.py
script:
- echo "Generating primitive description json and pipelines"
- python .travis/genreate-pipelines-json.py
- python .travis/generate-primitive-json.py
after_success:
- echo "Generated succeed, now pushing files"
# - .travis/push.sh
env:
  global:
    secure: JUJDUqkny/5uMtuX4BhYg9fOgx+nKzbbvr0s6/Pusyy+XTw4G6AjpuWCH/3VMI6ggnQZP7+jRlWeI2zkUXJ34kPONDYs0uCBv55UKP8avJKrXRoXG4rxwuWehspDjAoOPBKvT1qmtxlnH1ms0TEB7i5N3X6M2ghgryAVpEtKn55RtKkPeRMqo7nBpWXzrDlKI+bGW94TWtkcTSh9PoXQKy/PYa6bND5c1feWvccSDX48Pk+9fg5U0U3p4a5w6qZrJjSNCnj9FYeYGyKAX8bPxloyTWQnojinFCg65sWxj+Hj76Lk96JJMDxC2CEDzgG/kfeYUZ9P5yrAh2N/MjjEjWz/Ec3bY2JmMSsvMi3EufWCeZFMzGHL/NrAW1Ri/id5zVxphENgJ/MBdfboRhxhMDxH7e8i98kcG77OTcFaiGwTBOcNEggcRLQTuWn1EVotK2v660Ju+7mmHzYgWuL7CznRmfZRDZYtKIDWlz2oWV5eXUCXjubvimJfha933kWhDekh9g40qtdkPb/ewTmUvy9snop7icytBa2BKd7hqf9+HinG0pALG/fJfopmZTxKYSTsOcCOeU6ze/4zVK52GCek8hjS/URouwOrzu4CIaMA76bUMyTpHWo+9KRjEIHH9aRiE0MJq+nUaGkGMvKa1AocYvuiax3H7fHbQetkcbw=
