sudo: required
language: python
python:
- 3.6.6
install:
  - sudo apt-get update
  # We do this conditionally because it saves us some downloading if the
  # version is the same.
  - wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  # Useful for debugging any issues with conda
  - conda info -a
  - sudo apt-get install libtcmalloc-minimal4
  - export LD_PRELOAD="/usr/lib/libtcmalloc_minimal.so.4"
  - conda create --name dsbox-cleaner-env python=3.6
  - source activate dsbox-cleaner-env
  - pip install -e git+https://gitlab.com/datadrivendiscovery/common-primitives@fa865a1babc190055cb2a17cbdcd5b37e6f5e774#egg=common-primitives --progress-bar off
  - pip install stopit --progress-bar off
  - pip install fancyimpute==0.3.1 --progress-bar off
  - pip install langdetect --progress-bar off

script:
  - python -W ignore -m unittest discover

